### ISSUE TITLE
Unexpected panic occurs when time does not have a `-p` flag

### ISSUE THREAD

**Issue by zimeg** [zimeg/emporia-time#112]
Adventures into NixOS prove that the builtin `time` might not treat `-p` as a POSIX standard 😳

```
$ ./etime sleep 2
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/zimeg/emporia-time/pkg/times.parseTimeResults({0x0?, 0x2?})
        /home/ez/programming/etime/pkg/times/time.go:74 +0x29c
github.com/zimeg/emporia-time/pkg/times.TimeExec({{0xc000124130, 0x2, 0x2}, {{0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0, {0x0, ...}, ...}})
        /home/ez/programming/etime/pkg/times/time.go:59 +0x29e
github.com/zimeg/emporia-time/cmd.Run({{0xc000124130, 0x2, 0x2}, {{0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0, {0x0, ...}, ...}}, ...)
        /home/ez/programming/etime/cmd/etime.go:35 +0xbc
main.main()
        /home/ez/programming/etime/main.go:33 +0x2d8
```

**Comment by zimeg** [comment]
This is also an incorrect reliance on having a `/usr/bin/time` path!

https://github.com/zimeg/emporia-time/blob/2d823463284783c9fb49394a944624f658b4cf05/pkg/times/stopwatch.go#L50

**Comment by zimeg** [comment]
TIL about `\` to escape shell overrides? This is `darwin` magic 🪄

```
$ time -p sleep 2
zsh: command not found: -p
-p sleep 2  0.00s user 0.00s system 65% cpu 0.007 total
$ \time -p sleep 2
real 2.01
user 0.00
sys 0.00
```

**Comment by zimeg** [comment]
📝 The note on NixOS missing `-p` wasn't so right. That was related to that `darwin` magic which is moreso the powers of `zsh`.

A bit of confusion happened with `man time` showing "time functions for gawk" 🤔

**Comment by zimeg** [comment]
📝 For future reference these were some of the interesting `$PATH` to time since

```sh
$ which time
time: shell reserved word
```

Most of linux has:

```sh
/usr/bin/time
```

Nix might use something like:

```sh
/run/current-system/sw/bin/time
/nix/store/4ri3mpbq3xmlnqndvk7xfzv1q4g02was-time-1.9  # Might be from 'nix shell nixpkgs#time' but GNU
```

**Comment by zimeg** [comment]
☝️ `/nix/store/4ri3mpbq3xmlnqndvk7xfzv1q4g02was-time-1.9/share/info/time.info`

```man
1.6 Running the 'time' Command
==============================

The format of the 'time' command is:

     time [option...] COMMAND [ARG...]

   'time' runs the program COMMAND, with any given arguments ARG....
When COMMAND finishes, 'time' displays information about resources used
by COMMAND (on the standard error output, by default).  If COMMAND exits
with non-zero status or is terminated by a signal, 'time' displays a
warning message and the exit status or signal number.

   Options to 'time' must appear on the command line before COMMAND.
Anything on the command line after COMMAND is passed as arguments to
COMMAND.

'-p'
'--portability'
     Use the POSIX format.

```
